name: Deploy Django App

on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables and write key
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" || "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "DEPLOY_HOST=${{ secrets.STAGING_SERVER_HOST }}" >> $GITHUB_ENV
            echo "${{ secrets.STAGING_SSH_KEY }}" > key.pem
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DEPLOY_HOST=${{ secrets.PRODUCTION_SERVER_HOST }}" >> $GITHUB_ENV
            echo "${{ secrets.PRODUCTION_SSH_KEY }}" > key.pem
          fi
          chmod 600 key.pem

      - name: Debug SSH Key File
        run: |
          echo "First line of key.pem:"
          head -n 1 key.pem
          echo "Last line of key.pem:"
          tail -n 1 key.pem
          file key.pem

      - name: Deploy to ${{ env.ENVIRONMENT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ubuntu
          key: key.pem
          script: |
            cd /var/www/brandaids
            git pull origin ${{ github.ref_name }}
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --settings=brandaids.settings.${{ env.ENVIRONMENT }}
            python manage.py collectstatic --noinput --settings=brandaids.settings.${{ env.ENVIRONMENT }}
            sudo systemctl restart gunicorn_brandaids