name: Deploy Django App

on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging' || github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    name: Deploy to Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH Key
        run: |
          echo "${{ secrets.STAGING_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ubuntu
          key_path: key.pem
          script: |
            cd /var/www/brandaids
            git pull origin staging
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --settings=brandaids.settings.staging
            python manage.py collectstatic --noinput --settings=brandaids.settings.staging
            sudo systemctl restart gunicorn_brandaids

  deploy-production:
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    name: Deploy to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH Key
        run: |
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ubuntu
          key_path: key.pem
          script: |
            cd /var/www/brandaids
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --settings=brandaids.settings.production
            python manage.py collectstatic --noinput --settings=brandaids.settings.production
            sudo systemctl restart gunicorn_brandaids
