name: Deploy Django App

on:
  push:
    branches:
      - staging
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" || "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "HOST=staging.111110100.com" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "HOST=production.111110100.com" >> $GITHUB_ENV
          fi

      - name: Setup SSH
        run: |
          if [[ "$ENVIRONMENT" == "staging" ]]; then
            echo "${{ secrets.STAGING_SSH_KEY }}" > key.pem
          else
            echo "${{ secrets.PRODUCTION_SSH_KEY }}" > key.pem
          fi
          chmod 600 key.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
